apiVersion: apps/vi
kind: Deployment
metadata:
  name:ums-find-service
  labels:
    app: ums-find-service
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: ums-find-service
    template:
      metadata:
        labels:
          app: ums-find-service

      spec:
        containers:
          - name: ums-find-service
            image: ums
            ports:
              -containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ums-find-service
  labels:
    name: ums-find-service
  spec:
    type: LoadBalancer
    ports:
      - port: 8080
    selector:
      app: ums-find-service